### ISSUE TITLE
R studio crashes after last line 

### ISSUE THREAD

**Issue by auenbauer** [bwlewis/correlation-regularization#1]
I was trying to reproduce your analysis based on your blog post with my own list of 109 equity tickers and their daily prices from 2013-01-01 to yesterday. 

All seemed to be going well at first. The prices downloaded (except for 3 tickers where I got some error messages) and the plot for the eigenvalues is looking almost similar to yours (with a somewhat lower first value actually). 

![image](https://user-images.githubusercontent.com/14974013/29614991-88cab06a-880c-11e7-9586-2e5314894ee6.png)

The problem arises when I run the last line of code:

> graphjs(g, vertex.size=0.2, vertex.shape=colnames(X), edge.alpha=0.5)

Before that line I do not receive any noticeable error messages and in the following is a screenshot of the Data I have:

![image](https://user-images.githubusercontent.com/14974013/29617490-56c0aa76-8815-11e7-9120-91084a129aa6.png)
 

When I run the last line of code R Studio freezes forever and I have tried to run this code on two machines. 

Sorry if my explanation is not a good one. I am happy to contribute more data or the code. All I would have to do is to change my ticker list first. 

Thank you.

**Comment by bwlewis** [comment]
Can you send me the version of rstudio and R that you're using and I will try to reproduce?

also, oddly, things work great for me using the latest aversion of chrome...the fact that it works in IE but not chrome is strange.

**Comment by auenbauer** [comment]
R version 3.3.3 (2017-03-06)
R Studio Version 1.0.136 

...the chrome problem most likely is on my end (company IT or so..) and  the plot works fine in chrome on my laptop

Let me know if I should send you the code I am using.

thank you very much for your quick response and help!

**Comment by auenbauer** [comment]
I was able to run the code now on your and then on my own tickers. THX

**Comment by bwlewis** [comment]
Thanks for the update. I tested it and got it to work on a friend's Windows 10 laptop with the latest chrome and rstudio (and it seems to run very well in Microsoft Edge browser too).

I'm not sure what went wrong, but there are OpenGL rendering issues on Windows for some browsers and versions of RStudio out there. See for example the comments in these threejs bugs: https://github.com/bwlewis/rthreejs/issues/68 and  https://github.com/bwlewis/rthreejs/issues/59

Anyway glad it's working.

Also! See the updated example, I forgot to scale the precision matrix (issue #2). It's just a minor change.
